-- Migration 003: Populate teams table with all world countries
-- Run this in Supabase SQL Editor

-- =============================================
-- PART 1: Add is_active column and unique constraint
-- =============================================

ALTER TABLE teams ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false;

-- Add unique constraint on team_name if not exists
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teams_team_name_key') THEN
    ALTER TABLE teams ADD CONSTRAINT teams_team_name_key UNIQUE (team_name);
  END IF;
END $$;

-- Mark existing teams as active (participant teams)
UPDATE teams SET is_active = true WHERE id IN (1, 2, 3, 4);

-- =============================================
-- PART 2: Insert all world countries (FIFA members + territories)
-- =============================================

INSERT INTO teams (team_name, flag, is_active) VALUES
-- Europe (UEFA)
('Albania', '🇦🇱', false),
('Andorra', '🇦🇩', false),
('Armenia', '🇦🇲', false),
('Austria', '🇦🇹', false),
('Azerbaijan', '🇦🇿', false),
('Belarus', '🇧🇾', false),
('Belgium', '🇧🇪', false),
('Bosnia and Herzegovina', '🇧🇦', false),
('Bulgaria', '🇧🇬', false),
('Croatia', '🇭🇷', false),
('Cyprus', '🇨🇾', false),
('Czech Republic', '🇨🇿', false),
('Denmark', '🇩🇰', false),
('England', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', false),
('Estonia', '🇪🇪', false),
('Faroe Islands', '🇫🇴', false),
('Finland', '🇫🇮', false),
('Georgia', '🇬🇪', false),
('Germany', '🇩🇪', false),
('Gibraltar', '🇬🇮', false),
('Greece', '🇬🇷', false),
('Hungary', '🇭🇺', false),
('Iceland', '🇮🇸', false),
('Ireland', '🇮🇪', false),
('Israel', '🇮🇱', false),
('Italy', '🇮🇹', false),
('Kazakhstan', '🇰🇿', false),
('Kosovo', '🇽🇰', false),
('Latvia', '🇱🇻', false),
('Liechtenstein', '🇱🇮', false),
('Lithuania', '🇱🇹', false),
('Luxembourg', '🇱🇺', false),
('Malta', '🇲🇹', false),
('Moldova', '🇲🇩', false),
('Monaco', '🇲🇨', false),
('Montenegro', '🇲🇪', false),
('Netherlands', '🇳🇱', false),
('North Macedonia', '🇲🇰', false),
('Northern Ireland', '🇬🇧', false),
('Poland', '🇵🇱', false),
('Portugal', '🇵🇹', false),
('Romania', '🇷🇴', false),
('Russia', '🇷🇺', false),
('San Marino', '🇸🇲', false),
('Scotland', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', false),
('Serbia', '🇷🇸', false),
('Slovakia', '🇸🇰', false),
('Slovenia', '🇸🇮', false),
('Spain', '🇪🇸', false),
('Sweden', '🇸🇪', false),
('Switzerland', '🇨🇭', false),
('Turkey', '🇹🇷', false),
('Ukraine', '🇺🇦', false),
('Wales', '🏴󠁧󠁢󠁷󠁬󠁳󠁿', false),

-- South America (CONMEBOL)
('Argentina', '🇦🇷', false),
('Bolivia', '🇧🇴', false),
('Brazil', '🇧🇷', false),
('Chile', '🇨🇱', false),
('Colombia', '🇨🇴', false),
('Ecuador', '🇪🇨', false),
('Paraguay', '🇵🇾', false),
('Peru', '🇵🇪', false),
('Uruguay', '🇺🇾', false),
('Venezuela', '🇻🇪', false),

-- North/Central America & Caribbean (CONCACAF)
('Antigua and Barbuda', '🇦🇬', false),
('Bahamas', '🇧🇸', false),
('Barbados', '🇧🇧', false),
('Belize', '🇧🇿', false),
('Bermuda', '🇧🇲', false),
('Canada', '🇨🇦', false),
('Cayman Islands', '🇰🇾', false),
('Costa Rica', '🇨🇷', false),
('Cuba', '🇨🇺', false),
('Curaçao', '🇨🇼', false),
('Dominica', '🇩🇲', false),
('Dominican Republic', '🇩🇴', false),
('El Salvador', '🇸🇻', false),
('Grenada', '🇬🇩', false),
('Guatemala', '🇬🇹', false),
('Guyana', '🇬🇾', false),
('Haiti', '🇭🇹', false),
('Honduras', '🇭🇳', false),
('Jamaica', '🇯🇲', false),
('Mexico', '🇲🇽', false),
('Nicaragua', '🇳🇮', false),
('Panama', '🇵🇦', false),
('Puerto Rico', '🇵🇷', false),
('Saint Kitts and Nevis', '🇰🇳', false),
('Saint Lucia', '🇱🇨', false),
('Saint Vincent and the Grenadines', '🇻🇨', false),
('Suriname', '🇸🇷', false),
('Trinidad and Tobago', '🇹🇹', false),
('USA', '🇺🇸', false),
('US Virgin Islands', '🇻🇮', false),

-- Africa (CAF)
('Algeria', '🇩🇿', false),
('Angola', '🇦🇴', false),
('Benin', '🇧🇯', false),
('Botswana', '🇧🇼', false),
('Burkina Faso', '🇧🇫', false),
('Burundi', '🇧🇮', false),
('Cameroon', '🇨🇲', false),
('Cape Verde', '🇨🇻', false),
('Central African Republic', '🇨🇫', false),
('Chad', '🇹🇩', false),
('Comoros', '🇰🇲', false),
('Congo', '🇨🇬', false),
('DR Congo', '🇨🇩', false),
('Djibouti', '🇩🇯', false),
('Egypt', '🇪🇬', false),
('Equatorial Guinea', '🇬🇶', false),
('Eritrea', '🇪🇷', false),
('Eswatini', '🇸🇿', false),
('Ethiopia', '🇪🇹', false),
('Gabon', '🇬🇦', false),
('Gambia', '🇬🇲', false),
('Ghana', '🇬🇭', false),
('Guinea', '🇬🇳', false),
('Guinea-Bissau', '🇬🇼', false),
('Ivory Coast', '🇨🇮', false),
('Kenya', '🇰🇪', false),
('Lesotho', '🇱🇸', false),
('Liberia', '🇱🇷', false),
('Libya', '🇱🇾', false),
('Madagascar', '🇲🇬', false),
('Malawi', '🇲🇼', false),
('Mali', '🇲🇱', false),
('Mauritania', '🇲🇷', false),
('Mauritius', '🇲🇺', false),
('Morocco', '🇲🇦', false),
('Mozambique', '🇲🇿', false),
('Namibia', '🇳🇦', false),
('Niger', '🇳🇪', false),
('Nigeria', '🇳🇬', false),
('Rwanda', '🇷🇼', false),
('São Tomé and Príncipe', '🇸🇹', false),
('Sierra Leone', '🇸🇱', false),
('Somalia', '🇸🇴', false),
('South Africa', '🇿🇦', false),
('South Sudan', '🇸🇸', false),
('Sudan', '🇸🇩', false),
('Tanzania', '🇹🇿', false),
('Togo', '🇹🇬', false),
('Tunisia', '🇹🇳', false),
('Uganda', '🇺🇬', false),
('Zambia', '🇿🇲', false),
('Zimbabwe', '🇿🇼', false),

-- Asia (AFC)
('Afghanistan', '🇦🇫', false),
('Australia', '🇦🇺', false),
('Bahrain', '🇧🇭', false),
('Bangladesh', '🇧🇩', false),
('Bhutan', '🇧🇹', false),
('Brunei', '🇧🇳', false),
('Cambodia', '🇰🇭', false),
('China', '🇨🇳', false),
('Chinese Taipei', '🇹🇼', false),
('Guam', '🇬🇺', false),
('Hong Kong', '🇭🇰', false),
('India', '🇮🇳', false),
('Indonesia', '🇮🇩', false),
('Iran', '🇮🇷', false),
('Japan', '🇯🇵', false),
('Jordan', '🇯🇴', false),
('Kuwait', '🇰🇼', false),
('Kyrgyzstan', '🇰🇬', false),
('Laos', '🇱🇦', false),
('Lebanon', '🇱🇧', false),
('Macau', '🇲🇴', false),
('Malaysia', '🇲🇾', false),
('Maldives', '🇲🇻', false),
('Mongolia', '🇲🇳', false),
('Myanmar', '🇲🇲', false),
('Nepal', '🇳🇵', false),
('North Korea', '🇰🇵', false),
('Oman', '🇴🇲', false),
('Pakistan', '🇵🇰', false),
('Palestine', '🇵🇸', false),
('Philippines', '🇵🇭', false),
('Qatar', '🇶🇦', false),
('Saudi Arabia', '🇸🇦', false),
('Singapore', '🇸🇬', false),
('South Korea', '🇰🇷', false),
('Sri Lanka', '🇱🇰', false),
('Syria', '🇸🇾', false),
('Tajikistan', '🇹🇯', false),
('Thailand', '🇹🇭', false),
('Timor-Leste', '🇹🇱', false),
('Turkmenistan', '🇹🇲', false),
('United Arab Emirates', '🇦🇪', false),
('Uzbekistan', '🇺🇿', false),
('Vietnam', '🇻🇳', false),
('Yemen', '🇾🇪', false),

-- Oceania (OFC)
('American Samoa', '🇦🇸', false),
('Cook Islands', '🇨🇰', false),
('Fiji', '🇫🇯', false),
('New Caledonia', '🇳🇨', false),
('New Zealand', '🇳🇿', false),
('Papua New Guinea', '🇵🇬', false),
('Samoa', '🇼🇸', false),
('Solomon Islands', '🇸🇧', false),
('Tahiti', '🇵🇫', false),
('Tonga', '🇹🇴', false),
('Vanuatu', '🇻🇺', false)

ON CONFLICT (team_name) DO NOTHING;

-- =============================================
-- PART 3: Verify
-- =============================================
SELECT COUNT(*) as total_teams FROM teams;
SELECT * FROM teams WHERE is_active = true;
